on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto Presentation
        run: |
          quarto render index.qmd

      - name: Create deployment directory
        run: |
          mkdir -p _site
          cp -r index.html index_files/ images/ _site/
          cp .nojekyll _brand.yml styling.scss _site/
          cp *.png _site/ || true
          cp manifest.json _site/ || true

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
          branch: gh-pages
